version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: autosys
      POSTGRES_PASSWORD: 5432
      POSTGRES_DB: autosys
    ports:
      - "5432:5432"
  opcua-server-1:
    build: ./server-emu
    container_name: opcua-server-1
    ports:
      - "4841:4840"
    restart: unless-stopped
  opcua-server-2:
    build: ./server-emu
    container_name: opcua-server-2
    ports:
      - "4842:4840"
    restart: unless-stopped