spring:
    application:
      name: autosys
    server:
      port: 8080
    web:
      resources:
        static-locations: classpath:/static/
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      prefixes:
        css: classpath:/static/CSS/
        js: classpath:/static/JS/
      suffixes:
        css: .css
        js: .js
    servlet:
      path: /
    influx:
      url: http://localhost:8086
      token: ${INFLUXDB_TOKEN}
      org: mirea
      bucket: my-bucket