spring:
    application:
      name: autosys
    server:
      port: 8080
    web:
      resources:
        static-locations: classpath:/static/
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      prefixes:
        css: classpath:/static/CSS/
        js: classpath:/static/JS/
      suffixes:
        css: .css
        js: .js
    servlet:
      path: /
    datasource:
      url: jdbc:postgresql://localhost:5432/autosys
      username: autosys
      password: 5432
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect